"""``tombstone init``: detect the project shape, write tombstone.yaml, create .tombstone/."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import time
from collections.abc import Callable
from dataclasses import asdict, dataclass, field
from pathlib import Path

from tombstone.cli import EXIT_OK, command, emit
from tombstone.config import CONFIG_FILENAME, CONFIG_SCHEMA_VERSION, Installation, parse_config

_DEFAULT_OUT_OF_SCOPE = [
    "database backups and snapshots",
    "write-ahead logs and replicas",
    "embedding-provider-side request logs",
]


@dataclass
class Detected:
    langchain: bool = False
    record_manager: bool = False
    chroma_dirs: list[str] = field(default_factory=list)
    faiss_files: list[str] = field(default_factory=list)
    qdrant_dirs: list[str] = field(default_factory=list)
    pg_dsn: bool = False
    adapter_dirs: list[str] = field(default_factory=list)
    sqlite_caches: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


_SKIP_PARTS = {".venv", "venv", "node_modules", ".git", "site-packages", ".tombstone"}


def detect_project(root: Path) -> Detected:
    """Look for LangChain usage, Chroma/FAISS/Qdrant dirs, a PG_DSN, and peft adapter dirs."""
    det = Detected(pg_dsn=bool(os.environ.get("PG_DSN") or os.environ.get("DATABASE_URL")))
    lc_re = re.compile(r"^\s*(from|import)\s+langchain", re.M)
    rm_re = re.compile(r"RecordManager|langchain(?:_core)?\.indexes|from langchain_core\.indexing")
    seen = 0
    for p in root.rglob("*"):
        if any(part in _SKIP_PARTS for part in p.parts):
            continue
        if p.suffix == ".py" and p.is_file() and seen < 2000:
            seen += 1
            try:
                text = p.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            if lc_re.search(text):
                det.langchain = True
            if rm_re.search(text):
                det.record_manager = True
        elif p.name == "chroma.sqlite3":
            det.chroma_dirs.append(str(p.parent.relative_to(root)))
        elif p.name == "adapter_config.json":
            det.adapter_dirs.append(str(p.parent.relative_to(root)))
        elif p.suffix in {".faiss", ".index"} and p.is_file():
            det.faiss_files.append(str(p.relative_to(root)))
        elif p.name == "meta.json" and (p.parent / "collection").is_dir():
            det.qdrant_dirs.append(str(p.parent.relative_to(root)))
        elif p.name in {".langchain.db", "langchain.db"}:
            det.sqlite_caches.append(str(p.relative_to(root)))
    for lst in (
        det.chroma_dirs,
        det.adapter_dirs,
        det.faiss_files,
        det.qdrant_dirs,
        det.sqlite_caches,
    ):
        lst.sort()
    return det


def _suffix(i: int) -> str:
    return "" if i == 0 else str(i)


def render_config(det: Detected, scope: str = "default") -> str:
    lines = [
        "# Generated by `tombstone init`. Edit freely; re-run init to regenerate (a backup is kept).",
        f"version: {CONFIG_SCHEMA_VERSION}",
        f"scope: {scope}",
        "lineage: { backend: sqlite, path: ./.tombstone/lineage.db }",
        "",
        "stores:",
        '  - { name: "docs", kind: docstore, path: ./.tombstone/docstore.sqlite }',
    ]
    for i, d in enumerate(det.chroma_dirs):
        lines.append(
            f'  - {{ name: "chroma:{Path(d).name or "kb"}{_suffix(i)}", kind: chroma, '
            f"path: ./{d}, embedding: all-MiniLM-L6-v2 }}"
        )
    for i, f in enumerate(det.faiss_files):
        lines.append(
            f'  - {{ name: "faiss:{Path(f).stem}{_suffix(i)}", kind: faiss, '
            f"path: ./{f}, embedding: all-MiniLM-L6-v2 }}"
        )
    for i, d in enumerate(det.qdrant_dirs):
        lines.append(
            f'  - {{ name: "qdrant:{Path(d).name}{_suffix(i)}", kind: qdrant, '
            f"path: ./{d}, collection: kb, embedding: all-MiniLM-L6-v2 }}"
        )
    if det.pg_dsn:
        lines.append(
            '  - { name: "pgvector:kb", kind: pgvector, dsn: env:PG_DSN, table: documents, '
            "embedding: all-MiniLM-L6-v2 }"
        )
    for c in det.sqlite_caches:
        lines.append(f'  - {{ name: "exact-cache", kind: cache_exact, path: ./{c} }}')
    for i, d in enumerate(det.adapter_dirs):
        lines.append(
            f'  - {{ name: "lora/{Path(d).name}{_suffix(i)}", kind: adapter, '
            f"path: ./{d}, shards: 1, base_model: Qwen/Qwen2.5-0.5B }}"
        )
    lines += [
        "",
        "erase:",
        "  require_confirm: true",
        "  reclaim_timeout_s: 600",
        "  semantic_probe_budget: 5",
        "",
        "model:",
        "  base: Qwen/Qwen2.5-0.5B",
        "  unlearn: exact",
        "",
        "# Required. Copied onto every receipt: the layers this tool cannot reach (Hard Rule 2).",
        "out_of_scope:",
    ]
    lines += [f'  - "{s}"' for s in _DEFAULT_OUT_OF_SCOPE]
    return "\n".join(lines) + "\n"


def backup_existing(path: Path) -> Path | None:
    if not path.is_file():
        return None
    stamp = time.strftime("%Y%m%dT%H%M%S")
    backup = path.with_name(f"{path.name}.bak.{stamp}")
    n = 0
    while backup.exists():
        n += 1
        backup = path.with_name(f"{path.name}.bak.{stamp}.{n}")
    shutil.copy2(path, backup)
    if backup.read_bytes() != path.read_bytes():  # pragma: no cover - defensive
        raise OSError(f"backup of {path} to {backup} is not byte-identical; refusing to overwrite")
    return backup


def run_init(root: Path, scope: str = "default", force: bool = False) -> dict[str, object]:
    root = root.resolve()
    detected = detect_project(root)
    cfg_path = root / CONFIG_FILENAME
    backup = None
    written = False
    if cfg_path.is_file() and not force:
        # Validate what's there; keep it.
        parse_config(cfg_path.read_text(encoding="utf-8"), cfg_path)
    else:
        backup = backup_existing(cfg_path)
        text = render_config(detected, scope)
        parse_config(text, cfg_path)  # never write something we cannot read back
        cfg_path.write_text(text, encoding="utf-8")
        written = True
    inst = Installation(root / ".tombstone")
    inst.ensure()
    # A lineage db with the schema applied, so `status` works immediately.
    from tombstone.lineage.store import LineageStore

    store = LineageStore.open_sqlite(inst.lineage_db_path)
    store.close()
    gitignore = root / ".gitignore"
    needed = [".tombstone/"]
    existing = gitignore.read_text(encoding="utf-8") if gitignore.is_file() else ""
    missing = [n for n in needed if n not in existing.splitlines()]
    if missing:
        with gitignore.open("a", encoding="utf-8") as fh:
            if existing and not existing.endswith("\n"):
                fh.write("\n")
            fh.write("# tombstone state: pepper, keys, ledger, journal, lineage db\n")
            fh.write("\n".join(missing) + "\n")
    return {
        "config": str(cfg_path),
        "written": written,
        "backup": str(backup) if backup else None,
        "state_dir": str(inst.root),
        "detected": detected.to_dict(),
    }


@command("init", "detect the project, write tombstone.yaml, create .tombstone/ (pepper, keys)")
def _setup(p: argparse.ArgumentParser) -> Callable[[argparse.Namespace], int]:
    p.add_argument("--path", default=".", help="project root (default: cwd)")
    p.add_argument("--scope", default="default", help="tenant scope name")
    p.add_argument("--force", action="store_true", help="regenerate config (backup is kept)")

    def run(ns: argparse.Namespace) -> int:
        result = run_init(Path(ns.path), ns.scope, ns.force)
        det = result["detected"]
        assert isinstance(det, dict)
        summary = [
            f"config:    {result['config']} ({'written' if result['written'] else 'kept existing'})",
            f"state dir: {result['state_dir']} (pepper 0600, ed25519 keys, ledger, journal)",
        ]
        if result["backup"]:
            summary.append(f"backup:    {result['backup']}")
        parts: list[str] = []
        if det.get("langchain"):
            parts.append("langchain")
        if det.get("record_manager"):
            parts.append("RecordManager")
        for key, label in (
            ("chroma_dirs", "chroma"),
            ("faiss_files", "faiss"),
            ("qdrant_dirs", "qdrant"),
            ("adapter_dirs", "adapters"),
            ("sqlite_caches", "sqlite-caches"),
        ):
            items = det.get(key)
            if isinstance(items, list) and items:
                parts.append(f"{label}×{len(items)}")
        if det.get("pg_dsn"):
            parts.append("PG_DSN")
        summary.append(
            "detected:  "
            + (", ".join(parts) if parts else "nothing yet (add stores to tombstone.yaml)")
        )
        summary.append("")
        summary.append("next: wrap your vector store —")
        summary.append("  from tombstone.integrations.langchain import TombstoneVectorStore")
        summary.append('  vs = TombstoneVectorStore.from_config("chroma:kb", embeddings)')
        summary.append("then stamp documents at ingest and run `tombstone status`.")
        emit(ns, "\n".join(summary), result)
        return EXIT_OK

    return run
